version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm install -g bower
      - bower install
      - npm install -g gulp
  build:
    commands:
      - gulp
artifacts:
  files:
    - dist/*
  discard-paths: yes